# Generated by Django 4.2.5 on 2023-10-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
